-- BORRAR TODO EN ORDEN

DROP PACKAGE MODULO_SELECCION_COMPRA;
DROP PACKAGE MODULO_VIAJE;
DROP PACKAGE MODULO_OBSERVACION;
DROP PACKAGE MODULO_ANALISIS;

DROP TRIGGER sc_sumar_precio;
DROP TRIGGER fecha_caracteristica;
DROP TRIGGER fecha_disponibilidad;
DROP TRIGGER check_familiares_recursivos;

DELETE FROM PERTENENCIA;
DELETE FROM CARACTERISTICA;
DELETE FROM ASISTENCIA;
DELETE FROM MEDIO_PAGO;
DELETE FROM PAQUETE_TURISTICO;
DELETE FROM OBSERVACION;
DELETE FROM DISPONIBILIDAD;
DELETE FROM PAGO;
DELETE FROM PCR;
DELETE FROM SERVICIO;
DELETE FROM FAMILIAR;
DELETE FROM ALIANZA;
DELETE FROM VENTA;
DELETE FROM CLIENTE;
DELETE FROM MANTENIMIENTO;
DELETE FROM PROVEEDOR;
DELETE FROM COMPETIDOR;
DELETE FROM EMPRESA;
DELETE FROM PAIS;
DELETE FROM DESTINO_TURISTICO;
DELETE FROM TERRESTRE;
DELETE FROM CRUCERO;
DELETE FROM TRANSPORTE;


DROP TABLE PERTENENCIA;
DROP TABLE CARACTERISTICA;
DROP TABLE ASISTENCIA;
DROP TABLE MEDIO_PAGO;
DROP TABLE PAQUETE_TURISTICO;
DROP TABLE OBSERVACION;
DROP TABLE DISPONIBILIDAD;
DROP TABLE PAGO;
DROP TABLE PCR;
DROP TABLE SERVICIO;
DROP TABLE FAMILIAR;
DROP TABLE ALIANZA;
DROP TABLE VENTA;
DROP TABLE CLIENTE;
DROP TABLE MANTENIMIENTO;
DROP TABLE PROVEEDOR;
DROP TABLE COMPETIDOR;
DROP TABLE EMPRESA;
DROP TABLE PAIS;
DROP TABLE DESTINO_TURISTICO;
DROP TABLE TERRESTRE;
DROP TABLE CRUCERO;
DROP TABLE TRANSPORTE;

DROP SEQUENCE tra_id_seq;
DROP SEQUENCE des_id_seq;
DROP SEQUENCE pai_id_seq;
DROP SEQUENCE emp_id_seq;
DROP SEQUENCE man_id_seq;
DROP SEQUENCE cli_id_seq;
DROP SEQUENCE ven_id_seq;
DROP SEQUENCE ali_id_seq;
DROP SEQUENCE ser_id_seq;
DROP SEQUENCE pcr_id_seq;
DROP SEQUENCE pag_id_seq;
DROP SEQUENCE dis_id_seq;
DROP SEQUENCE obs_id_seq;
DROP SEQUENCE paq_id_seq;
DROP SEQUENCE med_id_seq;
DROP SEQUENCE asi_id_seq;

DROP TYPE TDA_MANTENIMIENTO FORCE;
DROP TYPE DATOS FORCE;
DROP TYPE FECHA FORCE;
DROP TYPE PRECIO FORCE;