-- BORRAR TODO EN ORDEN

DROP PACKAGE MODULO_SELECCION_COMPRA;

DROP TRIGGER sc_sumar_precio;
DROP TRIGGER fecha_caracteristica;
DROP TRIGGER fecha_disponibilidad;
DROP TRIGGER check_familiares_recursivos;

DROP TABLE PERTENENCIA;
DROP TABLE CARACTERISTICA;
DROP TABLE ASISTENCIA;
DROP TABLE MEDIO_PAGO;
DROP TABLE PAQUETE_TURISTICO;
DROP TABLE OBSERVACION;
DROP TABLE DISPONIBILIDAD;
DROP TABLE PAGO;
DROP TABLE PCR;
DROP TABLE SERVICIO;
DROP TABLE FAMILIAR;
DROP TABLE ALIANZA;
DROP TABLE VENTA;
DROP TABLE CLIENTE;
DROP TABLE MANTENIMIENTO;
DROP TABLE PROVEEDOR;
DROP TABLE COMPETIDOR;
DROP TABLE EMPRESA;
DROP TABLE PAIS;
DROP TABLE DESTINO_TURISTICO;
DROP TABLE TERRESTRE;
DROP TABLE CRUCERO;
DROP TABLE TRANSPORTE;

DROP SEQUENCE tra_id; 
DROP SEQUENCE des_id; 
DROP SEQUENCE pai_id; 
DROP SEQUENCE emp_id; 
DROP SEQUENCE man_id; 
DROP SEQUENCE cli_id; 
DROP SEQUENCE ven_id; 
DROP SEQUENCE ali_id; 
DROP SEQUENCE ser_id; 
DROP SEQUENCE pcr_id; 
DROP SEQUENCE pag_id; 
DROP SEQUENCE dis_id; 
DROP SEQUENCE obs_id; 
DROP SEQUENCE paq_id; 
DROP SEQUENCE med_id; 
DROP SEQUENCE asi_id; 

DROP TYPE TDA_MANTENIMIENTO FORCE;
DROP TYPE DATOS FORCE;
DROP TYPE FECHA FORCE;
DROP TYPE PRECIO FORCE;